---
project_name: wice

before:
  hooks:
  - go mod tidy
  - go generate ./...

builds:
- id: wice
  main: ./cmd/wice
  binary: wice
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  - arm
  goarm:
  - "6"
  - "7"
- id: wicectl
  main: ./cmd/wicectl
  binary: wicectl
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  - arm
  goarm:
  - "6"
  - "7"

archives:
- builds:
  - wice
  - wicectl

  format_overrides:
  - goos: windows
    format: zip

nfpms:
- vendor: stv0g
  homepage: https://github.com/stv0g/wice/
  maintainer: Steffen Vogel <post@steffenvogel.de>
  license: Apache 2.0
  formats:
  - apk
  - deb
  - rpm
  contents:
  # manpages
  - src: "./manpage/wice*.1"
    dst: "/usr/share/man/man1"
  # bash
  - src: "./contrib/completion/bash/exo"
    dst: "/usr/share/bash-completion/completions"
  # zsh
  - src: "./contrib/completion/zsh/_exo"
    dst: "/usr/share/zsh/vendor-completions/_exo"

dockers:
- use: buildx
  dockerfile: Dockerfile.scratch
  goos: linux
  goarch: amd64
  image_templates:
  - "stv0g/{{ .ProjectName }}:latest-amd64"
  - "stv0g/{{ .ProjectName }}:v{{ .Major }}-amd64"
  - "stv0g/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
  - "stv0g/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/stv0g/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/stv0g/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0

- use: buildx
  dockerfile: Dockerfile.scratch
  goos: linux
  goarch: arm64
  image_templates:
  - "stv0g/{{ .ProjectName }}:latest-arm64v8"
  - "stv0g/{{ .ProjectName }}:v{{ .Major }}-arm64v8"
  - "stv0g/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64v8"
  - "stv0g/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8"
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/stv0g/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/stv0g/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0

- use: buildx
  dockerfile: Dockerfile.scratch
  goos: linux
  goarch: arm
  goarm: "6"
  image_templates:
  - "stv0g/{{ .ProjectName }}:latest-armv6"
  - "stv0g/{{ .ProjectName }}:v{{ .Major }}-armv6"
  - "stv0g/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-armv6"
  - "stv0g/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-armv6"
  build_flag_templates:
  - --platform=linux/arm/v6
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/stv0g/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/stv0g/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0

- use: buildx
  dockerfile: Dockerfile.scratch
  goos: linux
  goarch: arm
  goarm: "7"
  image_templates:
  - "stv0g/{{ .ProjectName }}:latest-armv7"
  - "stv0g/{{ .ProjectName }}:v{{ .Major }}-armv7"
  - "stv0g/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-armv7"
  - "stv0g/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-armv7"
  build_flag_templates:
  - --platform=linux/arm/v7
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/stv0g/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/stv0g/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0

docker_manifests:
- name_template: stv0g/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - stv0g/{{ .ProjectName }}:{{ .Version }}-amd64
  - stv0g/{{ .ProjectName }}:{{ .Version }}-armv6
  - stv0g/{{ .ProjectName }}:{{ .Version }}-armv7
  - stv0g/{{ .ProjectName }}:{{ .Version }}-arm64v8

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
