# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: build

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y coturn protobuf-compiler

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Install dependencies
      run: |
        go install golang.org/x/lint/golint@latest
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Run wice build
      run: go build ./cmd/wice
      
    - name: Run vet
      run: go vet ./...

    - name: Run lint
      run: golint ./...

    - name: Run testing
      run: |
        sudo --preserve-env \
          env "PATH=$PATH" \
          go test -v ./...

    - uses: reviewdog/action-staticcheck@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        filter_mode: nofilter
        fail_on_error: true

    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      env:
        CODACY_REPORTER_TMP_FOLDER: .codacy
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage.out
        force-coverage-parser: go