on: 
- push
- pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.6'
    
    # Install all the dependencies
    - name: Install dependencies
      run: go get -u golang.org/x/lint/golint
        
    # Run build of the application
    - name: Run build
      run: make
      
    # Run vet on the code
    - name: Run vet
      run: go vet ./wice

    # Run lint on the code
    - name: Run lint
      run: golint ./wice

    # Run testing on the code
    - name: Run testing
      run: go test -v ./wice

    # Run static check
    - uses: reviewdog/action-staticcheck@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        filter_mode: nofilter
        fail_on_error: true

  # The "deploy" workflow
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [build] # Only run this workflow when "build" workflow succeeds
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} # Only run this workflow if it is master branch on push event
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: user/app:latest
