
on:
  release:
    types:
    - created

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.6
    - name: Make Directory with kgctl Binaries to Be Released
      run: make release
    - name: Publish Release
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        args: 'build/wice-*'
